{{ if .Capabilities.APIVersions.Has "argoproj.io/v1alpha1" }}
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dev
  namespace: argocd
  # Finalizer that ensures that project is not deleted until it is not referenced by any application
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # see more https://argo-cd.readthedocs.io/en/stable/operator-manual/declarative-setup/
  description: Dev Project
  sourceRepos:
  - '*'
  orphanedResources:
    warn: false
    ignore: []
  destinations:
  - namespace: '*'
    server: '*'
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
{{ end }}