{{ if .Capabilities.APIVersions.Has "argoproj.io/v1alpha1" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: thingsboard-redis-dev
  namespace: argocd
spec:
  project: dev
  source:
    helm:
      valueFiles:
      - values-thingsboard.yaml
    path: deploy/redis/16.12.0
    repoURL: git@github.com:haobinfei/gitops.git
    targetRevision: master
  destination:
    namespace: thingsboard
    server: https://192.168.122.51:6443
  syncPolicy:
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 2
    syncOptions:
    - CreateNamespace=true
{{ end }}