apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: my-daemon
spec:
  selector:
    matchLabels:
      app: my-daemon
      env: test
  template:
    metadata:
      labels:
        app: my-daemon
        env: test
    spec:
      containers:
      - name: nginx
        image: nginx:latest