{{ if .Capabilities.APIVersions.Has "argoproj.io/v1alpha1" }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ceph-csi-rbd-local
  namespace: argocd
spec:
  destination:
    namespace: ceph-csi
    server: https://kubernetes.default.svc
  project: local
  source:
    helm:
      valueFiles:
      - values-local.yaml
    path: deploy/ceph-csi-rbd/3.15.1
    repoURL: git@github.com:haobinfei/gitops.git
    targetRevision: master
  syncPolicy:
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 2
    syncOptions:
    - CreateNamespace=true
{{ end }}